name: "Hello World"
on:
  workflow_dispatch:
    inputs:
      who-to-greet: # id of input
        description: "Who to greet"
        required: true
        default: "World"
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt" # See 'Supported distributions' for available options
          java-version: "14"
      - uses: actions/checkout@master
        with:
          repository: rwth-acis/las2peer-akg
          path: ./
      - name: Extract branch name
        shell: bash
        run: ls
        id: extract_branch
      - name: Build jar
        run: |
          gradle wrapper --gradle-version 6.8.1 && ./gradlew jar
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            las2peer-akg/
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          python test.py
        env:
          key: ${{ secrets.key }} # if run.py requires passwords..etc, set it as secrets

