name: "Hello World"
on:
  workflow_dispatch:
    inputs:
      who-to-greet: # id of input
        description: "Who to greet"
        required: true
        default: "World"
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt" # See 'Supported distributions' for available options
          java-version: "14"
      - uses: actions/checkout@master
        with:
          repository: rwth-acis/las2peer-akg
          path: ./
      - name: Extract branch name
        shell: bash
        run: ls
        id: extract_branch
      - name: Build the Docker image
        run: |
          gradle wrapper --gradle-version 6.8.1 && ./gradlew jar
