name: "Hello World"
on:
  workflow_dispatch:
    inputs:
      who-to-greet: # id of input
        description: "Who to greet"
        required: true
        default: "World"
      sessionid: # id of input
        description: "Who to greet"
        required: true
        default: "World"
      repourl: # id of input
        description: "repourl"
        required: true
        default: "World"
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: "adopt" # See 'Supported distributions' for available options
          java-version: "14"
      - uses: actions/checkout@master
        with:
          repository: rwth-acis/${{ github.event.inputs.repourl }}
          path: ./
      - name: Extract branch name
        shell: bash
        run: ls
        id: extract_branch
      - name: Build jar
        run: |
          gradle wrapper --gradle-version 6.8.1 && ./gradlew jar
      - name: Read variable from file
        id: getvar
        run: echo "::set-output name=version::$(grep -o 'include[^"]*' settings.gradle  | awk -F"'" '{print $2}')"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            las2peer-akg/
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gradlefile
          path: |
            gradle.properties
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: dist-without-markdown
      - name: Download math result for job 1
        uses: actions/download-artifact@v2
        with:
          name: gradlefile
      - shell: bash
        run: |
          ls export/jars
      - shell: bash
        run: |
          ls export/
      - shell: bash
        run: |
          ls
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          pip install requests
      - name: execute py script # run the run.py to get the latest data
        run: |
          python test.py ${{ github.event.inputs.sessionid }}
