name: "Hello World"
on:
  workflow_dispatch:
    inputs:
      who-to-greet: # id of input
        description: "Who to greet"
        required: true
        default: "World"
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          name: rwth-acis/mobsos-evaluation-center
          ref: master
          path: ./
      - name: Extract branch name
        shell: bash
        run: ls
        id: extract_branch
      - name: Build the Docker image
        run: |
          docker build -t erdzan12/test:${{ steps.extract_branch.outputs.branch }} .
      - name: Push to registry
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PW: ${{ secrets.DOCKER_PW }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PW
          docker push erdzan12/test:${{ steps.extract_branch.outputs.branch }}
  notify:
    needs: say_hello
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://sleepy-cove-96643.herokuapp.com/oikjdsjkns"
          method: "POST"
