name: "Hello World"
on:
  workflow_dispatch:
    inputs:
      who-to-greet: # id of input
        description: "Who to greet"
        required: true
        default: "World"
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: rwth-acis/las2peer-akg
          path: ./
      - name: Extract branch name
        shell: bash
        run: ls
        id: extract_branch
      - name: Build the Docker image
        run: |
          gradlew build
